### ISSUE TITLE
About the version of Tensorflow

### ISSUE THREAD

**Issue by Sam1224** [xiaolinhan/ConGC#2]
I use tf==1.14.0, but in model_gcnn.py line 183, and layers.py line 12, the shape of x_temp_input (6d) is incompatible with seq.get_shape() (3d), I'm not sure if it could be auto-transformed by other versions of tensorflow, may I query about the version of tf you adopted.

**Comment by xiaolinhan** [comment]
Thanks for your interest! tf==1.14.0 works fine with ConGC model. There is something missing during the refactor phase in the code. We have updated them. Please try with the latest code. Thanks.

**Comment by Sam1224** [comment]
Thank you so much!
